### ISSUE TITLE
How to even load local skins?

### ISSUE THREAD

**Issue by GhostOps77** [zatrit/openmcskins2#24]
I can't find any proper documentation on how to do it. All i have done is added a local host, and i've put my skin's png into the `.minecraft/config/openmcskins/local/` directory. And all it did was load in some other skin that looks like a guy with a big moustache, in an armour (seems like a FALLBACK skin). Am i missing something here?

I use fabric loader, and MC version is 1.20.4

config file:
```toml
cacheTextures = true
verboseLogs = false
refreshOnConfigSave = true
loaderTimeout = 2.0
uuidMode = "OFFLINE"

[[hosts]]
type = "LOCAL"

[hosts.properties]
directory = "#{configDir}/openmcskins/local"

[[hosts]]
type = "MOJANG"

[[hosts]]
type = "FALLBACK"
```
